insert into location (lid, lname, laddress) values (1, 'Noll', '46927 Mifflin Junction');
insert into location (lid, lname, laddress) values (2, 'Karlee', '720 Daystar Lane');
insert into location (lid, lname, laddress) values (3, 'Malorie', '8 Corry Pass');
insert into location (lid, lname, laddress) values (4, 'Roscoe', '9427 Jenna Street');
insert into location (lid, lname, laddress) values (5, 'Joshuah', '50 Manufacturers Road');
insert into location (lid, lname, laddress) values (6, 'Loralyn', '6667 Holmberg Street');
insert into location (lid, lname, laddress) values (7, 'Vanny', '6321 Sage Avenue');
insert into location (lid, lname, laddress) values (8, 'Ive', '20792 Menomonie Terrace');
insert into location (lid, lname, laddress) values (9, 'Mervin', '0927 Buena Vista Center');
insert into location (lid, lname, laddress) values (10, 'Felice', '8 Bartillon Crossing');
